name: Fetch


on:
  # Daily at 12:06 PM UTC (12:06 AM Wellington time; first over the date line)
  schedule:
    - cron: '06 12 * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      # Allow commits to repo
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Find tomorrow's date (UTC), which is the new date (Wellington, NZ)
        id: today
        run: echo "today=$(date -v+1d +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Fetch Wordle JSON
        id: fetch-wordle
        run: |
          curl https://www.nytimes.com/svc/wordle/v2/${{ steps.today.outputs.today }}.json -o data/wordle/${{ steps.today.outputs.today }}.json

      - name: Commit Changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Fetch for ${{ steps.today.outputs.today }}